name: CMake CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake cmake-data

    - name: Configure CMake
      run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build _build

    - name: Install
      run: cmake --build _build --target install

    - name: Run tests
      run: cmake --build _build --target test -- ARGS=--verbose
